# Generated by Django 4.2.6 on 2023-12-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='содержимое'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_create',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата создания'),
        ),
    ]
